name: Automated Tests

on: 

jobs:
  jest:
    name: Jest Ubuntu
    runs-on: Ubuntu-latest
    steps:
       - uses: sctions/checkout@v4

       - uses: actions/setup-node@v4
         with:
            node-version: 'lts/hydrogen'

       - run: npm ci

       - run: npm test   